BEGIN TRANSACTION;
CREATE TABLE Accounts(accountid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, password TEXT);
INSERT INTO "Accounts" VALUES(1,'hp','qq');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('Version',1);
INSERT INTO "sqlite_sequence" VALUES('Accounts',1);
INSERT INTO "sqlite_sequence" VALUES('Colours',18);
CREATE TABLE Areas(areaid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, height INTEGER, width INTEGER);
CREATE TABLE Branches(branchid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, fkTree INTEGER, fkPrimaryStat INTEGER, fkSecondaryStat INTEGER);
CREATE TABLE AccountCharacter(accountcharacterid INTEGER PRIMARY KEY AUTOINCREMENT, fkCharacter INTEGER, fkAccount INTEGER);
CREATE TABLE CharacterBranch(characterbranchid INTEGER PRIMARY KEY AUTOINCREMENT, fkCharacter INTEGER, fkBranch INTEGER);
CREATE TABLE CharacterCluster(characterclusterid INTEGER PRIMARY KEY AUTOINCREMENT);
CREATE TABLE Characters(characterid INTEGER PRIMARY KEY AUTOINCREMENT, fkRace INTEGER, fkRoom INTEGER, name TEXT, description TEXT);
CREATE TABLE CharacterSkill(characterskillid INTEGER PRIMARY KEY AUTOINCREMENT, fkCharacter INTEGER, fkBranch INTEGER);
CREATE TABLE CharacterStat(characterstatid INTEGER PRIMARY KEY AUTOINCREMENT, fkCharacter INTEGER, fkStat INTEGER);
CREATE TABLE CharacterTree(charactertreeid INTEGER PRIMARY KEY AUTOINCREMENT, fkCharacter INTEGER, fkTree INTEGER);
CREATE TABLE Clusters(clusterid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE Colours(colourid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, code TEXT, colourstring TEXT, ansi INTEGER);
INSERT INTO "Colours" VALUES(2,'Restore','^','0;0m',1);
INSERT INTO "Colours" VALUES(3,'Dark Red','r','31m',1);
INSERT INTO "Colours" VALUES(4,'Dark Green','g','32m',1);
INSERT INTO "Colours" VALUES(5,'Dark Yellow','y','33m',1);
INSERT INTO "Colours" VALUES(6,'Dark Blue','b','34m',1);
INSERT INTO "Colours" VALUES(7,'Dark Purple','m','35m',1);
INSERT INTO "Colours" VALUES(8,'Dark Cyan','c','36m',1);
INSERT INTO "Colours" VALUES(9,'Grey','w','37m',1);
INSERT INTO "Colours" VALUES(10,'Dark Black','l','30m',1);
INSERT INTO "Colours" VALUES(11,'Light Red','R','1;31m',1);
INSERT INTO "Colours" VALUES(12,'Light blue','G','1;32m',1);
INSERT INTO "Colours" VALUES(13,'Light Yellow','Y','1;33m',1);
INSERT INTO "Colours" VALUES(14,'Light Blue','B','1;34m',1);
INSERT INTO "Colours" VALUES(15,'Light Magenta','M','1;35m',1);
INSERT INTO "Colours" VALUES(16,'Light Cyan','C','1;36m',1);
INSERT INTO "Colours" VALUES(17,'White','W','1;37m',1);
INSERT INTO "Colours" VALUES(18,'Light Black','L','1;30m',1);
CREATE TABLE Commands(commandid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, grantgroup INTEGER RESTRAINT grantgroup DEFAULT 1, highforce INTEGER RESTRAINT highforce DEFAULT 1, force INTEGER RESTRAINT force DEFAULT 1, lowforce INTEGER RESTRAINT lowforce DEFAULT 0);
CREATE TABLE Exits(exitid INTEGER PRIMARY KEY AUTOINCREMENT, dir INTEGER);
CREATE TABLE GrantGroups(grantgroupid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, defaultgrant INTEGER, implies INTEGER);
CREATE TABLE Permissions(permissionid INTEGER PRIMARY KEY AUTOINCREMENT, fkAccount INTEGER, fkCommand INTEGER, fkGrantGroup INTEGER, grant INTEGER);
CREATE TABLE Races(raceid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE Rooms(roomid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, fkArea INTEGER, fkSector INTEGER, width INTEGER, length INTEGER, height INTEGER);
CREATE TABLE Sectors(sectorid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, symbol TEXT, movecost INTEGER, water INTEGER);
CREATE TABLE Skills(skillid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, fkBranch INTEGER);
CREATE TABLE Stats(statid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, shortname TEXT);
CREATE TABLE Trees(treeid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, fkCluster INTEGER, fkPrimaryStat INTEGER, fkSecondaryStat INTEGER);
CREATE TABLE Version(version INTEGER PRIMARY KEY AUTOINCREMENT, versiontext TEXT, major INTEGER, minor INTEGER, micro INTEGER);
INSERT INTO "Version" VALUES(1,'0.1.0',0,1,0);
COMMIT;
